/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jeigen_JeigenJna */

#ifndef _Included_jeigen_JeigenJna
#define _Included_jeigen_JeigenJna
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
