/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jeigen_JeigenJna_Jeigen */

#ifndef _Included_jeigen_JeigenJna_Jeigen
#define _Included_jeigen_JeigenJna_Jeigen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_init
  (JNIEnv *, jclass);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    dense_multiply
 * Signature: (III[D[D[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_dense_1multiply
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    sparse_multiply
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_jeigen_JeigenJna_00024Jeigen_sparse_1multiply
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    sparse_dense_multiply
 * Signature: (IIII[D[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_sparse_1dense_1multiply
  (JNIEnv *, jclass, jint, jint, jint, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    dense_sparse_multiply
 * Signature: (III[DI[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_dense_1sparse_1multiply
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    svd_dense
 * Signature: (II[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_svd_1dense
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    jeigen_exp
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_jeigen_1exp
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    jeigen_log
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_jeigen_1log
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    ldlt_solve
 * Signature: (III[D[D[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_ldlt_1solve
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    fullpivhouseholderqr_solve
 * Signature: (III[D[D[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_fullpivhouseholderqr_1solve
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    allocateSparseMatrix
 * Signature: (III[I[I[D)I
 */
JNIEXPORT jint JNICALL Java_jeigen_JeigenJna_00024Jeigen_allocateSparseMatrix
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jintArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    getSparseMatrixStats
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_getSparseMatrixStats
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    getSparseMatrix
 * Signature: (I[I[I[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_getSparseMatrix
  (JNIEnv *, jclass, jint, jintArray, jintArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    freeSparseMatrix
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_freeSparseMatrix
  (JNIEnv *, jclass, jint);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    dense_dummy_op1
 * Signature: (II[D[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_dense_1dummy_1op1
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    dense_dummy_op2
 * Signature: (III[D[D[D)V
 */
JNIEXPORT void JNICALL Java_jeigen_JeigenJna_00024Jeigen_dense_1dummy_1op2
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     jeigen_JeigenJna_Jeigen
 * Method:    sparse_dummy_op2
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_jeigen_JeigenJna_00024Jeigen_sparse_1dummy_1op2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
